BaSP-m2023/nico-megarocket-app

package-lock.json
package.json
src/Components/Footer/index.js
src/Components/Header/index.js
src/Components/Layout/index.js

React router fifth version added to the project

BaSP-MR-84: React Router created

---

src/Components/Members/Form/MembersForm.js
src/Components/Members/TableMember/index.js
src/Components/Members/index.js

Now the member list is automatically updated after the submit event

BaSP-MR-99: MemberList update

---

src/Components/Trainers/FormEditTrainers/FormEditTrainer.jsx
src/Components/Trainers/FormTrainers/index.jsx
src/Components/Trainers/TableTrainers/index.jsx
src/Components/Trainers/index.js

It was possible to solve the error that error messages appeared under the inputs in the Trainers forms, both to add a new one and to edit an existing one.

BaSP-MR-121: Error onBlur in forms inputs for Trainers

---

src/Components/Members/EditForm/MembersEditForm.js
src/Components/Members/EditMember/index.js
src/Components/Members/TableMember/index.js
src/Components/Members/index.js

Now it shows the information of the member to edit[fixed]

BaSP-MR-110: Edit form fixes

---

src/Components/Shared/Inputs/InputError/error-placeholder-input.css
src/Components/Shared/Inputs/InputError/index.jsx
src/Components/Shared/Inputs/InputPlaceholder/index.jsx
src/Components/Shared/Inputs/InputPlaceholder/placeholder-input.css
src/Components/Shared/index.js
src/Components/Trainers/TableTrainers/index.jsx

The global inputs were designed where it shows me an error (with a red border and text), and another where a text can be seen inside the input (placeholder).

BaSP-MR-86: Inputs error and nomarl input with placeholder

---

src/Components/Trainers/TableTrainers/index.jsx
src/Components/Trainers/index.js

Fixed problem with forms in Trainer.
Bug fixed: two forms appeared instead of just one.

BaSP-MR-80: fixes in forms for Trainers

---

src/Components/Activities/Table/Index.jsx
src/Components/Admins/index.js
src/Components/Classes/index.js
src/Components/Members/index.js
src/Components/Subscriptions/Table/Index.jsx
src/Components/SuperAdmins/index.jsx
src/Components/Trainers/index.js

I added toats error in all proyect

BaSP-MR-113: Add toast error

---

src/Components/Shared/ButtonForm/button.module.css
src/Components/Shared/ButtonForm/index.js
src/Components/Shared/index.js

I create buttons form edit and delete in Shared

BaSP-MR-94: Create buttons edit and delete

---

src/Components/Activities/AddActivity/Index.jsx
src/Components/Activities/Table/Index.jsx
src/Components/Activities/Table/TableActivity.jsx
src/Components/Shared/Loader/index.jsx
src/Components/Shared/Loader/loader.module.css
src/Components/Shared/index.js

BaSP-MR-97: Loading component created

---

src/Components/Home/index.js
src/Components/Shared/Button/button.module.css
src/Components/Shared/Button/index.js
src/Components/Shared/index.js

BaSP-MR-88: Create Global Button

---

src/Components/Admins/index.js
src/Components/SuperAdmins/index.jsx

As instructed I changed the fetch petitions of the components Admin and SuperAdmin by adding /api.

BaSP-MR-124: Modify fetch petitions on ONE entitie

---

src/Components/Activities/AddActivity/Index.jsx
src/Components/Activities/Table/Index.jsx
src/Components/Activities/Table/TableActivity.jsx
src/Components/Admins/Form/index.js
src/Components/Classes/index.js
src/Components/Members/Form/MembersForm.js
src/Components/Members/index.js
src/Components/Subscriptions/AddSubscription/Index.jsx
src/Components/Subscriptions/Table/Index.jsx
src/Components/Subscriptions/Table/TableSubscription.jsx
src/Components/Trainers/FormEditTrainers/FormEditTrainer.jsx
src/Components/Trainers/FormTrainers/index.jsx
src/Components/Trainers/index.js

According to the requirements stated in ticket 126, the "/api" endpoint has been added to each FETCH method in the project.

BaSP-MR-126: Modify fetch petition of ALL ENTITIES.

---

src/Components/Shared/Button/button.module.css
src/Components/Shared/Table/index.js

I added buttons form edit and delete in TableComponent

BaSP-MR-125: Add ButtonForm component in TableComponent

---

src/Components/Trainers/FormTrainers/index.jsx
src/Components/Trainers/TableTrainers/index.jsx
src/Components/Trainers/index.js

The current PR is related to ticket 123. To resolve it, the TRAINERS component needs to have the DELETE functionality implemented correctly.
All the requirements listed in the ticket have been completed.
Problem: The DELETE function uses the ID stored in the TRAINERS state. When a trainer is added, the generated ID of the response is not saved in the TRAINERS state. Therefore, when performing the ADD action without refreshing the page, all trainers stored in the TRAINERS state do not have an ID, which makes the DELETE functionality impossible to use.
Solution: Every time an ADD action is performed on trainers, the ID is obtained from the response, and the complete trainer is stored within the TRAINERS state.

BaSP-MR-123: Delete functionality BUG

---

src/Components/Shared/AddButton/index.js

I removed the Link from react-router-dom and replace it with a function inside an OnClick that when this button is pressed this will redirect you to each entity form.

BaSP-MR-130: Updated button with a function

---

src/Components/Shared/Modals/ModalConfirm/index.js

I updated modal confirm and added a modal success

BaSP-MR-131: Update modal confirm

---

src/Components/Shared/Inputs/NormalInput/index.jsx

Implement the type label on NormalInput button.

BaSP-MR-134: Type modification on Normal Input

---

src/Components/Admins/Form/form.module.css
src/Components/Admins/Form/index.js

i implemented the form with shared components and correct the style to make it look more similar to the figma design

BaSP-MR-92:Form styles with shared inputs and buttons

---

package.json

MR-140: Update package

---

src/Components/Admins/Form/index.js

i made a change requested by the QA team

BaSP-MR-144: Change on form admin logic

---

src/Components/Subscriptions/FormSubscription/Index.jsx

Now you can edit subscriptions successfully!

BaSP-MR-135: fixes to edit subscription

---

package-lock.json
package.json
src/index.js
src/redux/rootReducer.js
src/redux/store.js

Implementation of
-Redux
-Redux-thunk

BaSP-MR-163: redux implementation

---

package-lock.json
package.json
src/redux/store.js

I added applyMeddleware and devTools

BaSP-MR-164: Add applyMeddleware and devTools

---

src/Components/Shared/Modals/ModalConfirm/index.js
src/Components/Shared/Table/index.js

I changed a ModalSucces from ModalConfirm to TableComponent

BaSP-MR-172: Modify Modal Confirm

---

src/Components/SuperAdmins/Form/form.module.css
src/Components/SuperAdmins/Form/index.jsx
src/Components/SuperAdmins/index.jsx
src/redux/superAdmins/reducer.js
src/redux/superAdmins/thunks.js

Now when you enter a right or wrong input on the form it'll show you successfully the modal success or the toast error

BaSP-MR-173- Hotfix on Super admin form modals and styles

---

src/Components/Classes/index.js
src/Components/Layout/index.js
src/Components/Members/Form/MembersForm.js
src/Components/Navbar/Navbar.js
src/Components/Users/Admin/classes/index.js
src/Components/Users/Admin/index.js
src/Components/Users/Admin/members/index.js
src/Components/Users/Admin/profile/index.js
src/Components/Users/Admin/subscriptions/index.js
src/Components/Users/Admin/trainers/index.js
src/Components/Users/Member/activities/index.js
src/Components/Users/Member/classes/index.js
src/Components/Users/Member/index.js
src/Components/Users/Member/profile/index.js

BaSP-MR-198: admin and members logic

---

src/Components/Shared/Inputs/NormalInput/index.jsx

I modify input with errors and register

BaSP-MR-207: Modify Input

---

src/Components/Shared/Button/index.js

I modify type button to Submit

BaSP-MR-206: Modify Button

---

src/Components/Members/Form/MembersForm.js
src/Components/Members/Form/form.module.css
src/Components/Shared/Button/index.js
src/Components/Shared/Inputs/NormalInput/disable-input.module.css
src/Components/Shared/Inputs/NormalInput/index.jsx

I created a form in member with Hook Form and Joi validation

BaSP-MR-177: Members Form

---

src/Components/Shared/Button/index.js
src/Components/Shared/Inputs/NormalInput/disable-input.module.css
src/Components/Shared/Inputs/NormalInput/index.jsx
src/Components/SuperAdmins/Form/form.module.css
src/Components/SuperAdmins/Form/index.jsx

Also i did some modifications on Inputs component styles file in to make input stay in its defined position when an error validation ocurres. And modifications on Form superadmin styles.

BaSP-MR-182: react-hook-form implementation on SuperAdmin entity

---

src/Components/Shared/Button/button.module.css

Updated Form Buttons Styles.
- General redesign
- Hover effects added

BaSP-MR-210: Updated Buttons Styles

---

src/Components/Classes/Form/formClasses.module.css
src/Components/Classes/Form/index.js
src/Components/Shared/Inputs/OptionInput/index.jsx
src/Components/Shared/Inputs/OptionInput/option-input.module.css

Also made some adjustment on OptionInput component to make functional the select option input with the hook form. Made minimal styles modification on classes form.

BaSP-MR-178:react hook form implementation on classes entity

---

src/Components/Subscriptions/FormSubscription/Index.jsx
src/redux/subscriptions/thunks.js

I created a subscription form with React Hook Form and Joi Validation.

BaSP-MT-180: Subscription Form

---

README.md

Updated the README file detailing the objectives of the week 14 issue.

BaSP-MR-201: Update Readme file

---

jsconfig.json
src/Components/Activities/FormActivities/index.jsx
src/Components/Activities/index.js
src/Components/Admins/Form/index.js
src/Components/Admins/index.js
src/Components/Classes/Form/index.js
src/Components/Classes/index.js
src/Components/Members/Form/MembersForm.js
src/Components/Members/index.js
src/Components/Subscriptions/FormSubscription/Index.jsx
src/Components/Subscriptions/index.js
src/Components/SuperAdmins/Form/index.jsx
src/Components/SuperAdmins/index.jsx
src/Components/Trainers/FormTrainers/index.jsx
src/Components/Trainers/index.js
src/Components/Users/Admin/classes/index.js
src/Components/Users/Admin/members/index.js
src/Components/Users/Admin/subscriptions/index.js
src/Components/Users/Admin/trainers/index.js

File jsconfig created, baseUrl is: "src", paths of import absoluts are: Components and redux. The activities and admin entities were modified as an example.

BaSP-MR-200: import absoluts created

---

src/Components/Classes/Form/index.js
src/Components/Shared/Inputs/OptionInput/index.jsx

option select input on class form fixed. Made some changes on the shared option input and Class form

BaSP-MR-215: class fixed

---

src/Components/Users/Member/activities/Cards/cards.module.css
src/Components/Users/Member/modals/activityModal.jsx
src/Components/Users/Member/modals/activityModal.module.css

Changes made to match the figma design

BaSP-MR-219: fixing some modal styles

---

src/Components/Shared/Table/index.js
src/Components/Users/Member/activities/Cards/cards.module.css

Made a change on shared Table Component for functionality bug and added a hover on Card component on members

BaSP-MR-218: Classes bug fixed and activity card hover

---

src/Components/Classes/Form/index.js
src/Components/Shared/Inputs/OptionInput/index.jsx

input Option added to class, input Hour was modified.

BaSP-MR-217: input option added to class

---

src/Components/Shared/Inputs/OptionInput/index.jsx

BaSP-MR-217: option input fixed

---

src/Components/Users/Member/activities/Cards/cards.module.css
src/Components/Users/Member/activities/index.js
src/Components/Users/Member/modals/activityModal.jsx
src/Components/Users/Member/modals/activityModal.module.css

Implement component card in Member-Activity and fix visual errors

MR-220: implement component cards

---

package-lock.json
package.json
src/helper/firebase/index.js

I install firebase and create helper

BaSP-MR-225: Install firebase and create helper

---

src/helper/firebase/index.js

I deleted measurementId in firebaseConfig

BaSP-MR-243: Fix firebase config

---

src/routes/privateRoute.js

I created route folder and privateRoute component.

BaSP-MR-233: Create private routes

---

src/redux/auth/reducer.js
src/routes/auth.js

I created a auth route in routes.

BaSP-MR-246: Create auth route

---

src/redux/admins/thunks.js
src/redux/members/thunks.js
src/redux/superAdmins/thunks.js
src/redux/trainers/thunks.js

Thunks was modified, it added property headers with a token object.

BaSP-MR-256:  thunks modified, headers added

---

src/routes/members.js
src/routes/superAdmin.js

created two new files on Routes folder which each one defines its routes redirection and what to render to each different user (SuperAdmin or Member in this case)

MR-255: Routes for superadmin and member

---

src/Components/Activities/FormActivities/index.jsx
src/Components/Activities/index.js
src/Components/Admins/Form/index.js
src/Components/Admins/index.js
src/Components/Auth/Login/index.js
src/Components/Classes/Form/index.js
src/Components/Classes/index.js
src/Components/Members/Form/MembersForm.js
src/Components/Members/index.js
src/Components/Navbar/Navbar.js
src/Components/Shared/AddButton/index.js
src/Components/Shared/Button/index.js
src/Components/Shared/ButtonForm/index.js
src/Components/Shared/Containers/index.js
src/Components/Shared/Inputs/InputError/index.jsx
src/Components/Shared/Inputs/InputPlaceholder/index.jsx
src/Components/Shared/Inputs/NormalInput/index.jsx
src/Components/Shared/Inputs/OptionInput/index.jsx
src/Components/Shared/Loader/index.jsx
src/Components/Shared/Modals/ModalConfirm/index.js
src/Components/Shared/Modals/ModalSuccess/index.js
src/Components/Shared/Modals/ToastError/index.js
src/Components/Shared/Table/index.js
src/Components/Users/Admin/profile/index.js
src/Components/Users/Member/activities/Cards/index.jsx
src/Components/Users/Member/activities/index.js
src/Components/Users/Member/classes/index.js
src/Components/Users/Member/modals/activityModal.jsx
src/Components/Users/Member/profile/index.js

Added data-testid to all components in the application

BaSP2023-MR-251: Add data-testids

---

src/Components/Shared/Table/index.js

Fix date subscription to format 'MM-DD-YYYY'

BaSP-MR-230: Fix date subscription

---

src/Components/Layout/index.js

BaSP-MR-250: Restructuring Layout

---

src/Components/Users/Trainer/classes/classes.module.css
src/Components/Users/Trainer/classes/index.js
src/Components/Users/Trainer/profile/index.js
src/Components/Users/Trainer/profile/mockData.json
src/Components/Users/Trainer/profile/profile.module.css
src/routes/admin.js
src/routes/index.js
src/routes/trainer.js

I created index, admin and trainer route.

BaSP-MR-254: Index, Admin and Trainer Routes

---

src/Components/Auth/LogOut/index.js
src/Components/Header/index.js
src/Components/Layout/index.js
src/Components/Navbar/Navbar.js
src/index.js
src/routes/auth.js
src/routes/index.js
src/routes/privateRoute.js
src/routes/superAdmin.js

Update routes folder and within files passing them via props rendering it member access

BaSP-MR-253: Navbar re organization

---

README.md

The Readme file was updated, notifying the implementation of libraries and tasks to be carried out in the problem of week 15.

BaSP-MR-260: Update Readme

---

src/Components/Shared/Containers/index.js
src/redux/classes/thunks.js
src/routes/auth.js

I modify the logic of the slots in the grid, so that when they join a class, the amount available is discounted.

BaSP-MR-240: Modify slots

---

src/Components/Auth/SignUp/index.jsx
src/Components/Members/Form/MembersForm.js

The normal input was replaced with a select input with options in the forms to create Members.

BaSP-MR-235: add select input in forms Member

---

src/Components/Trainers/FormTrainers/index.jsx
src/redux/trainers/thunks.js

BaSP-MR-277: token trainer in thunks fixed - form updated

---

src/Components/Shared/Containers/index.js
src/helper/firebase/index.js
src/redux/subscriptions/thunks.js

BaSP-MR-264: Modify Activity grid

---

src/Components/Auth/SignUp/index.jsx
src/Components/Auth/SignUp/signUp.module.css
src/Components/Shared/Inputs/OptionInput/option-input.module.css
src/Components/Trainers/FormTrainers/form.module.css
src/Components/Trainers/FormTrainers/index.jsx

- Trainer Create Form fixed! Now you can save your changes
- Trainer Modal Fixed. Now the modal show the correct message
- SignUp Title
- SignUp IsActive picker redesign

BaSP-MR-274: Fix Trainers Form/SignUp

---

src/Components/Shared/Containers/index.js
src/Components/Subscriptions/FormSubscription/Index.jsx
src/redux/classes/thunks.js
src/redux/subscriptions/actions.js
src/redux/subscriptions/reducer.js
src/redux/subscriptions/thunks.js

BaSP-MR-282: Fix subscription grid

---

src/Components/Auth/SignUp/index.jsx
src/Components/Auth/SignUp/signUp.module.css
src/redux/auth/thunks.js

- Now when you create a member shows a Modal Success.
- When you insert a email already used shows a Toast Error.

BaSP-MR-267: SignUp bug fixes!

---

src/Components/Members/Form/MembersForm.js
src/Components/Members/index.js
src/Components/Trainers/index.js
src/redux/members/thunks.js

- Members Table Toast Error fixed
- Trainers Table Toast Error fixed

BaSP-MR-278: members/trainers toast error fixed

---

src/redux/trainers/thunks.js

BaSP-MR-284: admin token hotfix

---

src/Components/Subscriptions/FormSubscription/Index.jsx
src/redux/subscriptions/thunks.js

With @Ginoboca1 fixed a form subscription.

BaSP-MR-292: Fix form

---

src/Components/Activities/FormActivities/index.jsx
src/Components/Activities/FormActivities/modalAdd.module.css
src/Components/Auth/Login/index.js
src/Components/Auth/Login/login.module.css
src/Components/Auth/RecoverPassword/index.js
src/Components/Auth/RecoverPassword/recoverPassword.module.css
src/Components/Classes/Form/formClasses.module.css
src/Components/Classes/Form/index.js
src/Components/Subscriptions/FormSubscription/Index.jsx
src/Components/Trainers/FormTrainers/form.module.css
src/Components/Trainers/FormTrainers/index.jsx

- Now all form buttons have the same order
- New link to SignUp in Login page
- Before when you pressed enter in the Login it took you to the recovery password. Now send the Form correctly
- Cancel button in Recover page

BaSP-MR-293: Form Buttons and fix in Login

---

src/Components/Users/Member/classes/index.js

I created a filter in activity schedule.

BaSP-MR-236: Filter schedule

---

src/Components/Classes/Form/index.js
src/redux/classes/thunks.js

BaSP-MR-319: Fix class form

---

src/Components/Auth/SignUp/index.jsx

I fixed membership input in sign up form.

BaSP-MR-312: Fix membership

---

src/Components/Auth/Login/index.js
src/Components/Auth/Login/login.module.css
src/Components/Members/Form/MembersForm.js
src/Components/Subscriptions/FormSubscription/Index.jsx
src/Components/Users/Admin/profile/profile.module.css
src/Components/Users/Member/profile/Form/index.js
src/Components/Users/Member/profile/Form/profile-form.module.css
src/Components/Users/Member/profile/index.js
src/Components/Users/Member/profile/mockData.json
src/Components/Users/Member/profile/profile.module.css
src/Components/Users/Trainer/profile/Form/index.js
src/Components/Users/Trainer/profile/Form/profile-form.module.css
src/Components/Users/Trainer/profile/index.js
src/Components/Users/Trainer/profile/mockData.json
src/Components/Users/Trainer/profile/profile.module.css
src/routes/admin.js
src/routes/members.js
src/routes/trainer.js

Styled Member and Trainer profile to show its own data. Create a form on each profile for the PUT petition.
Fix buttons position on Login component.
Hotfix on Subscription and Member's Form component. Now when you are an admin and want to edit a subscription or member the Date input shows an actual date.

BaSP-MR-311: Trainer and Member profiles

---

src/Components/Shared/ButtonForm/button.module.css
src/Components/Users/Admin/profile/index.js
src/Components/Users/Admin/profile/profile.module.css
src/Components/Users/Member/profile/index.js
src/Components/Users/Member/profile/profile.module.css
src/Components/Users/Trainer/profile/index.js
src/Components/Users/Trainer/profile/profile.module.css

On previous PR i made a change on a global component styles so it affected other parts of the page. In this PR that was corrected.

MR-325: Hotfix on edit button styles

---

src/Components/Shared/Inputs/OptionMultipleInput/index.js
src/Components/Shared/Inputs/OptionMultipleInput/option-multiple-input.module.css
src/Components/Shared/index.js
src/Components/Subscriptions/FormSubscription/Index.jsx
src/Components/Subscriptions/FormSubscription/modalAdd.module.css

I fixed the subscription form. Now you can add or remove one or more members.

BaSP-MR-318: Fix subs create and edit

---

src/Components/Shared/Table/index.js

I fixed the table, so that when it is an array, the first element is displayed and then the remaining length.

BaSP-MR-328: Fix table

---

src/Components/Trainers/FormTrainers/index.jsx

Repeat password input added to add trainer form and its validation.

BaSP-MR-317: repeat password input added

---

src/Components/Auth/SignUp/index.jsx

Field "repeat password" and its validation added to sign up form

BaSP-MR-315: sign up update

---

src/Components/Activities/FormActivities/index.jsx
src/Components/Activities/FormActivities/modalAdd.module.css
src/Components/Auth/Login/index.js
src/Components/Auth/Login/login.module.css
src/Components/Auth/RecoverPassword/recoverPassword.module.css
src/Components/Auth/SignUp/signUp.module.css
src/Components/Classes/Form/formClasses.module.css
src/Components/Classes/Form/index.js
src/Components/Members/Form/form.module.css
src/Components/Shared/Inputs/NormalInput/disable-input.module.css
src/Components/Shared/Inputs/NormalInput/index.jsx
src/Components/Shared/Inputs/OptionInput/index.jsx
src/Components/Shared/Inputs/OptionInput/option-input.module.css
src/Components/Shared/Inputs/OptionMultipleInput/index.js
src/Components/Shared/Inputs/OptionMultipleInput/option-multiple-input.module.css
src/Components/Subscriptions/FormSubscription/Index.jsx
src/Components/Subscriptions/FormSubscription/modalAdd.module.css
src/Components/Trainers/FormTrainers/form.module.css
src/Components/Trainers/FormTrainers/index.jsx

- Form's Redesign: now all forms has the same layout and more friendly interface animations.
- All Forms components has the same HTML element tags and buttons.
- CSS code optimization.
- Inputs Redesign: now all the inputs show and icon (In the next few days we will be adding new and more elements of the 
application).
- The padding and margin of the elements was modified, now there is a cohesion between them.

BaSP-MR-331: Forms update styles

---

src/Components/Shared/Table/index.js
src/Components/Shared/Table/table.module.css

BaSP-MR-294: pagination created

---

src/Components/Classes/Form/index.js
src/Components/Subscriptions/FormSubscription/Index.jsx
src/Components/Subscriptions/FormSubscription/modalAdd.module.css

I validate that the class subscription is not repeated. In addition, in case of editing the subscription, you can edit the class. 
Finally, only active members can be selected

BaSP-MR-335: Modify Subscription Form

---

src/Components/Auth/SignUp/index.jsx
src/Components/Trainers/FormTrainers/index.jsx

BaSP-MR-338: hotFixes member - trainer

---

src/Components/Classes/Form/index.js
src/Components/Users/Member/classes/index.js

I validated that the class is not repeated on the same day at the same time.

BaSP-MR-348: Fix class repeat

---

src/Components/Header/ProfileMenu/index.js
src/Components/Header/ProfileMenu/profileMenu.module.css
src/Components/Shared/ChangeImg/changeImg.module.css
src/Components/Shared/ChangeImg/index.js
src/Components/Users/Admin/profile/index.js
src/Components/Users/Admin/profile/profile.module.css
src/Components/Users/Member/profile/index.js
src/Components/Users/Member/profile/profile.module.css
src/Components/Users/Trainer/profile/index.js
src/Components/Users/Trainer/profile/profile.module.css

Update profile and redirect header name.

BaSP-MR-336: update profile and redirect header name

---

src/Components/Subscriptions/index.js

Button add subcription deleted

BaSP-MR-355: add subcription deleted

---

src/Components/Classes/Form/index.js
src/Components/Shared/Containers/index.js
src/Components/Subscriptions/FormSubscription/Index.jsx
src/Components/Users/Member/classes/classes.module.css
src/Components/Users/Member/classes/index.js

I fixed modal bug. Then, a subscription will be created when clicking on a class that doesn't have a subscription assigned.

BaSP-MR-290: Fix modal

---

src/Components/Shared/Containers/index.js

I fixed update class when a member join or leave class

BaSP-MR-359: Fix update class

---

src/Components/Members/Form/MembersForm.js

BaSP-MR-356: member update button fixed

---

src/Components/Admins/Form/index.js
src/Components/Auth/SignUp/index.jsx
src/Components/Trainers/FormTrainers/index.jsx

BaSP-MR-330: repeat password message

---

src/Components/Shared/Table/index.js

fix filter search. metod trim added.

BaSP-MR-339: fix filter search

---

src/Components/Shared/Table/index.js

BaSP-MR-338: toggle button fixed

---

public/assets/images/edit.svg
public/assets/images/profile.svg
src/Components/Auth/Login/login.module.css
src/Components/Users/Admin/profile/index.js
src/Components/Users/Admin/profile/profile.module.css
src/Components/Users/Member/profile/Form/profile-form.module.css
src/Components/Users/Member/profile/index.js
src/Components/Users/Member/profile/profile.module.css
src/Components/Users/Trainer/profile/index.js
src/Components/Users/Trainer/profile/profile.module.css
src/index.css

-Profiles pages Styles
-Form profiles Styles
-Forms buttons profiles now has the same order

BaSP-MR-354: profiles updated

---

src/Components/Members/Form/MembersForm.js
src/Components/Shared/Inputs/NormalInput/disable-input.module.css
src/Components/Shared/Table/table.module.css
src/Components/Trainers/FormTrainers/index.jsx
src/Components/Users/Admin/profile/Form/index.js
src/Components/Users/Member/profile/Form/index.js
src/Components/Users/Trainer/profile/Form/index.js

- Members, trainers and admins cannot edit his Email account.
- Changes Form profile buttons order

BaSP-MR-340: fix-profile

---

src/routes/admin.js
src/routes/auth.js
src/routes/members.js
src/routes/privateRoute.js
src/routes/superAdmin.js
src/routes/trainer.js

This PR is related to ticket MR-344, which required that the styles of the auth buttons should not be modified when accessing an unauthorized route.
IMPORTANT. After discussing with the team, it has been decided that in the case of accessing an undesired route, the user should remain unauthorized and be redirected to the "not allowed" route without switching their role.
To achieve this, when accessing an unauthorized route, the user will be redirected to the "not allowed" route specific to the role they logged in with.

BaSP-MR-344: Menu button shape

---

src/Components/Activities/FormActivities/index.jsx
src/Components/Activities/FormActivities/modalAdd.module.css
src/Components/Auth/Login/login.module.css
src/Components/Members/Form/MembersForm.js
src/Components/Shared/Inputs/TextArea/index.js
src/Components/Shared/Inputs/TextArea/text-area.module.css
src/Components/Shared/index.js
src/redux/activities/thunks.js

Deleted the isActive box containing the radio buttons to chose an option between true or false and replace it with an input type='hidden' that set isActive attribute to false by default.  
Fix thunks on Activity redux in order to improve the Edit and Create funcionality of the Activity's form.
Change the input type text of the description input to a textarea input.
Fix the color of the error pop on Login form that were change to white and the text wasn't watchable.

BaSP-MR-358: Fix activity 

---

src/Components/Users/Trainer/classes/classes.module.css
src/Components/Users/Trainer/classes/index.js

I added message when a trainer doesn't hace any class assigned

BaSP-MR-364: Trainer grid message

---

src/Components/Users/Trainer/classes/TableMembers/index.js
src/Components/Users/Trainer/classes/TableMembers/table-member.module.css

I added a message when members are not subscribed in a class

BaSP-MR-365: Message in Trainer's members table

---

src/Components/Shared/Modals/ModalInfo/index.js
src/Components/Shared/Modals/ModalInfo/modalInfo.module.css
src/Components/Shared/Table/index.js
src/Components/Shared/Table/table.module.css
src/Components/Shared/index.js

Change styles on subscription table member column when it says the quantity of member enrolled.
Now when you click member column on subscription table it'll show a modal with the information of the member that are subscripted to each class.

BaSP-MR-346: Members modal's subcription table info

---

src/Components/Activities/FormActivities/index.jsx
src/Components/Admins/Form/index.js
src/Components/Classes/Form/index.js
src/Components/Members/Form/MembersForm.js
src/Components/Shared/Modals/ModalSuccess/index.js
src/Components/Subscriptions/FormSubscription/Index.jsx
src/Components/Trainers/FormTrainers/index.jsx

- Now the recover password modal success show the correct message
- Updated confirm / success messages of all modals. Now they all show the same message format.

BaSP-MR-368: Modal confirm messages updated

---

src/Components/Home/home.module.css

BaSP-MR-379: Fix video

---

src/Components/Shared/Modals/ModalConfirm/index.js

BaSP-MR-377: Fix bug

---

src/Components/Auth/SignUp/index.jsx
src/redux/auth/thunks.js

I fixed message in sign up when exists DNI or Email.

BaSP-MR-380: Fix message in sign up

---

src/Components/Auth/LogOut/logout.module.css
src/Components/Navbar/Navbar.js
src/Components/Navbar/navbar.module.css
src/routes/auth.js

Fixed when you are on landing page and change to login or sign up and at the sidebar the Home link looks active with the selected one (login or sign up).
Deleted useless code on Navbar file because that were old logic for old buttons styles.
Add transition when the links are unhovered

BaSP-MR-386: Sidebar isActive fixed

---

src/Components/Auth/Login/index.js
src/Components/Auth/SignUp/index.jsx
src/Components/Shared/Modals/ModalSignUp/index.js
src/Components/Shared/Modals/ModalSignUp/modalSignUp.module.css
src/Components/Shared/index.js

When an account is logged and via url go to the landing page and then to the login or sign up section now it wouldn't show the form. If it goes to Login it will immediately redirect you to each role page and if it goes to the sign up page a modal will apear saying that there is already an account logged and to options, one to go to the menu and another to logout

BaSP-MR-391: Account manage on home

---

src/Components/Shared/Inputs/OptionInput/index.jsx
src/Components/Shared/Inputs/OptionInput/option-input.module.css
src/Components/Users/Member/classes/classes.module.css
src/Components/Users/Member/classes/index.js

The styles related to Option Inputs were modified. No libraries were applied for this purpose, so all changes were made using CSS only.

BaSP-MR-372: Option inputs styles

---

src/Components/Users/Admin/profile/profile.module.css
src/Components/Users/Member/profile/profile.module.css
src/Components/Users/Trainer/profile/profile.module.css

update styles button of profile.

BaSP-MR-392: update styles button of profile

---

src/Components/Shared/Modals/ModalInfo/index.js
src/Components/Shared/Modals/ModalInfo/modalInfo.module.css
src/Components/Shared/Table/index.js

app crashed when a subscription member array was empty so i added an extra if validation solving the mentioned bug. Also added on modal info an extra row indicating that 0 members are enrolled to that class when it is necessary

MR-396: subscription fixed when no member is enrolled to a class

---

src/Components/Users/Member/activities/Cards/cards.module.css
src/Components/Users/Member/activities/activities.module.css
src/Components/Users/Member/modals/activityModal.module.css

This PR is related to ticket 388. For its resolution it was required to improve the styles of the entire Activities sections including modal and cards. The page is not entierly designed for responsive use.

BaSP-MR-388: Member activities styles

---

src/Components/Header/header.module.css
src/Components/Header/index.js
src/Components/Shared/Loader/loader.module.css

It was decided to implement a link that redirects to Home in the Header component, and it was decided to add a border-radius to the loader to complement the aesthetics of the web.

BaSP-MR-361: add link to Home in Header and modify loader border

---

src/Components/Activities/FormActivities/index.jsx
src/Components/Admins/Form/index.js
src/Components/Members/Form/MembersForm.js
src/Components/Shared/Modals/ModalConfirm/index.js
src/Components/Shared/Modals/ModalConfirm/modalConfirm.module.css
src/Components/Shared/Modals/ModalInfo/index.js
src/Components/Shared/Modals/ModalInfo/modalInfo.module.css
src/Components/Subscriptions/FormSubscription/Index.jsx
src/Components/Trainers/FormTrainers/index.jsx
src/Components/Users/Admin/profile/Form/index.js
src/Components/Users/Member/modals/activityModal.jsx
src/Components/Users/Member/modals/activityModal.module.css
src/Components/Users/Member/profile/Form/index.js
src/Components/Users/Trainer/classes/TableMembers/index.js
src/Components/Users/Trainer/profile/Form/index.js
src/routes/superAdmin.js

i added an animation everytime a modal pops up or out also added loader on those form where wasn't applied.

BaSP-MR-320: Transitions/animations on modals and loaders

---

src/Components/Header/index.js
src/routes/auth.js

now when an an user/admin/etc is logged and press the logo to go to the landing page the nabvar will keep the routes/icons of each features that user is allowed to do on the app.

BaSP-MR-400: Navbar on home when user is logged

---

src/Components/Members/index.js
src/Components/Shared/AddButton/addButton.module.css
src/Components/Shared/AddButton/index.js
src/Components/Shared/Modals/ModalAllInfo/index.js
src/Components/Shared/Modals/ModalAllInfo/modalAllInfo.module.css
src/Components/Shared/Table/index.js
src/Components/Shared/Table/table.module.css
src/Components/Shared/index.js
src/Components/Subscriptions/index.js

table styles updated, new modal to info.

BaSP-MR-383: table styles updated

---

src/Components/Header/ProfileMenu/index.js
src/Components/Shared/ChangeImg/index.js
src/Components/Users/Admin/profile/index.js
src/Components/Users/Admin/profile/profile.module.css
src/Components/Users/Member/profile/index.js
src/Components/Users/Member/profile/profile.module.css
src/Components/Users/Trainer/profile/index.js
src/Components/Users/Trainer/profile/profile.module.css

BaSP-MR-387: profile img persistance for trainer and admin

---

src/Components/Trainers/FormTrainers/index.jsx

Joi validation has password and repeat password so i add an extra validation if it is and update trainer joi validation do not have those passwords attributes

BaSP-MR-399: Fix update trainer as Admin

---

src/Components/Admins/Form/form.module.css
src/Components/Admins/Form/index.js
src/Components/Layout/layout.module.css
src/Components/Navbar/navbar.module.css

Now the Admins forms has the same styles has another forms

BaSP-MR-398: SuperAdmin admin form styles

---

src/Components/Shared/Modals/ModalAllInfo/index.js
src/Components/Shared/Modals/ModalInfo/index.js

subscription broke the app when non trainer was added on a class so i added an extra validation in order to fix that.
Also fix button edit redirection path on activity modalInfo.

BaSP-MR-403: modals info adjustment

---

src/Components/Admins/Form/index.js
src/Components/Trainers/FormTrainers/index.jsx

fix password inputs on update admin form by changing Joi validation code

BaSP-MR-403: Admin Form Password fix

---

src/Components/Shared/ChangeImg/changeImg.module.css
src/Components/Shared/ChangeImg/index.js

BaSP-MR-402: picture size and file type errors manage

---

src/Components/Auth/SignUp/index.jsx

Input picture deleted of sign up.

BaSP-MR-409: input picture deleted of sign up

---

src/Components/Footer/footer.module.css
src/Components/Footer/index.js
src/Components/Shared/ButtonActive/index.js
src/Components/Shared/Containers/container.module.css
src/Components/Shared/TableMobile/index.js
src/Components/Users/Member/classes/classes.module.css
src/Components/Users/Member/classes/index.js
src/Components/Users/Trainer/classes/classes.module.css
src/Components/Users/Trainer/classes/index.js

grid of trainers and members now are responsive

BaSP-MR-406: grid responsive

---

src/Components/Activities/FormActivities/modalAdd.module.css
src/Components/Admins/Form/form.module.css
src/Components/Classes/Form/formClasses.module.css
src/Components/Members/Form/form.module.css
src/Components/Shared/ChangeImg/changeImg.module.css
src/Components/Shared/Inputs/OptionInput/option-input.module.css
src/Components/Shared/Inputs/OptionMultipleInput/option-multiple-input.module.css
src/Components/Subscriptions/FormSubscription/modalAdd.module.css
src/Components/Trainers/FormTrainers/form.module.css
src/Components/Users/Admin/profile/Form/profile-form.module.css
src/Components/Users/Admin/profile/profile.module.css
src/Components/Users/Trainer/profile/Form/profile-form.module.css

BaSP-MR-405: all form are now responsive

---

src/Components/Activities/FormActivities/index.jsx
src/Components/Activities/FormActivities/modalAdd.module.css
src/Components/Shared/ChangeImg/changeActivityImg.js
src/Components/Shared/ChangeImg/changeImg.module.css
src/Components/Shared/ChangeImg/index.js
src/Components/Shared/index.js
src/Components/Users/Member/activities/Cards/index.jsx
src/Components/Users/Member/activities/index.js

BaSP-MR-408: add picture to activity

---

src/Components/Header/header.module.css
src/Components/Shared/ChangeImg/changeImg.module.css
src/Components/Shared/ChangeImg/index.js
src/Components/Users/Admin/profile/profile.module.css
src/Components/Users/Member/profile/profile.module.css
src/Components/Users/Trainer/profile/profile.module.css

each profile responsive, modal 'changeImg' updated.

BaSP-MR-412: each profile responsive

---

src/Components/Auth/Login/index.js
src/Components/Auth/Login/login.module.css
src/Components/Auth/SignUp/index.jsx
src/Components/Auth/SignUp/signUp.module.css
src/Components/HamburguerMenu/hamburguer.module.css

change position of inputs on mobile version following what was ask on this bug report made by the QA Team

MR-414: [BUGFIX] Sign up inputs on responsive view

---

src/Components/Shared/ButtonActive/index.js

it work toggle button perfectly.

BaSP-MR-424: update toggle button

---

src/Components/Shared/Modals/ModalAllInfo/index.js
src/Components/Shared/Modals/ModalAllInfo/modalAllInfo.module.css
src/Components/Users/Member/activities/Cards/cards.module.css
src/Components/Users/Member/activities/Cards/index.jsx
src/Components/Users/Member/classes/index.js
src/Components/Users/Member/modals/activityModal.jsx
src/Components/Users/Member/modals/activityModal.module.css

fix modal info, fix styles card activities and filter of the grid.

BaSP-MR-428: fix filter grid member and style cards activities
